#!/usr/bin/python3 -u

#
# Copyright (C) 2018  Omer Akram
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

from autobahn.twisted import wamp
from autobahn.wamp import types as wamp_types
import txaio

from sbs.component import BrightnessServerSession


if __name__ == '__main__':
    txaio.start_logging(level='debug')
    session = BrightnessServerSession(wamp_types.ComponentConfig('realm1', {}))
    runner = wamp.ApplicationRunner(u'rs://localhost:5020', 'realm1')
    runner.run(session, auto_reconnect=True)
