$schema: https://raw.githubusercontent.com/crossbario/crossbar/master/crossbar.json
version: 2
controller: {}
workers:
- type: router
  realms:
  - name: deskconn
    roles:
    - name: anonymous
      permissions:
      - uri: ''
        match: prefix
        allow:
          call: true
          register: true
          publish: true
          subscribe: true
        disclose:
          caller: false
          publisher: false
        cache: true
  components:
  - type: class
    realm: deskconn
    classname: deskconn.components.brightness.ScreenBrightnessComponent
  transports:
  - type: universal
    endpoint:
      type: tcp
      port: 5020
    websocket:
      ws:
        type: websocket
#    web:
#      paths:
#        call:
#          type: caller
#          realm: deskconn
#          role: anonymous
  - type: rawsocket
    endpoint:
      type: unix
      path: $SNAP_COMMON/deskconn.sock
