$schema: https://raw.githubusercontent.com/crossbario/crossbar/master/crossbar.json
version: 2
controller: {}
workers:
- type: router
  realms:
  - name: deskconn
    roles:
    - name: anonymous
      permissions:
      - uri: 'org.deskconn.'
        match: prefix
        allow:
          call: true
          register: true
          publish: true
          subscribe: true
        disclose:
          caller: false
          publisher: false
        cache: true
  - name: pairing
    roles:
    - name: anonymous
      permissions:
      - uri: 'org.deskconn.pairing.'
        match: prefix
        allow:
          call: true
          register: true
        disclose:
          caller: false
          publisher: false
        cache: true

  components:
  - type: class
    realm: pairing
    classname: deskconn.components.pairing.PairingComponent
  transports:
  - type: universal
    endpoint:
      type: tcp
      port: 5020
    websocket:
      ws:
        type: websocket
    web:
      paths:
        call:
          type: caller
          realm: pairing
          role: anonymous
  - type: rawsocket
    endpoint:
      type: unix
      path: $SNAP_COMMON/deskconn.sock
