name: deskconn
version: git
summary: Expose your desktop functionalities over network
description: |
  Expose your desktop functionalities over network

grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64
    run-on: amd64

environment:
  PYTHONPATH: $PYTHONPATH:$SNAP_COMMON/crossbar-runtime-dir/lib/python3.6/site-packages

parts:
  launchers:
    plugin: dump
    source: .
    stage:
      - system.py
      - session.py
      - config.sh
    prime:
      - system.py
      - session.py
      - config.sh
  deskconn:
    plugin: python
    source: .
    python-packages:
      - dbus-python
      - xlib
      - evdev
    build-packages:
      - libdbus-1-dev
      - libdbus-glib-1-dev

apps:
  deskconn:
    command: system.py
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind
      - display-control
  session:
    command: session.py
    plugs:
      - network
      - network-bind
      - x11
      - unity7
      - desktop
  config:
    command: config.sh

plugs:
  deskconnd-sock-dir:
    content: socket-directory
    default-provider: deskconnd:sock-dir
    interface: content
    target: $SNAP_COMMON/deskconnd-sock-dir
  crossbar-runtime-dir:
    content: executables
    default-provider: crossbar:runtime-dir
    interface: content
    target: $SNAP_COMMON/crossbar-runtime-dir
