name: deskconn
version: git
summary: Expose your desktop functionalities over network
description: |
  Expose your desktop functionalities over network

grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: i386
    run-on: i386

  - build-on: armhf
    run-on: armhf

parts:
  launchers:
    plugin: dump
    source: .
    stage:
      - system.py
      - session.py
      - config.sh
    prime:
      - system.py
      - session.py
      - config.sh
  deskconn:
    plugin: python
    source: .
    requirements:
      - requirements.txt
    build-packages:
      - libdbus-1-dev
      - libdbus-glib-1-dev
      - libffi-dev
      - libssl-dev

apps:
  deskconn:
    command: python3 -u $SNAP/system.py
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind
      - display-control
  session:
    command: python3 -u $SNAP/session.py
    plugs:
      - network
      - network-bind
      - x11
      - unity7
      - desktop
  config:
    command: config.sh

plugs:
  deskconn-sock-dir:
    content: socket-directory
    default-provider: deskconnd:deskconn-sock-dir
    interface: content
    target: $SNAP_COMMON
