name: screen-brightness-server
version: '0.3'
summary: Expose screen brightness control to local http server
description: |
  Expose screen brightness control to local http server

  Currently only supports machines with Intel GPU.

grade: stable
confinement: devmode

architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: i386
    run-on: i386

parts:
  server:
    plugin: dump
    source: .
    prime:
      - start-crossbar
      - crossbar-config
  autobahn:
    plugin: python
    source: .
    requirements: requirements.txt

apps:
  server:
    command: start-crossbar
    daemon: simple
    restart-condition: never
    environment:
      PYTHONPATH: "$SNAP/lib/python3.5/site-packages:$PYTHONPATH"
