name: screen-brightness-server
version: '0.3'
summary: Expose screen brightness control to local http server
description: |
  Expose screen brightness control to local http server

  Currently only supports machines with Intel GPU.

grade: stable
confinement: devmode

architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: i386
    run-on: i386

parts:
  server:
    plugin: dump
    source: .
    prime:
      - start-crossbar
      - start-component
      - crossbar-config/*
      - sbs/*
  autobahn:
    plugin: python
    python-packages:
      - autobahn[asyncio]

apps:
  crossbar:
    command: start-crossbar
    daemon: simple
    restart-condition: always
    environment:
      PYTHONPATH: "$SNAP/crossbar:$PYTHONPATH"
  component:
    command: start-component
    daemon: simple

plugs:
  crossbar:
    interface: content
    content: executables
    default-provider: crossbar:crossbar
    target: $SNAP/crossbar
