name: screen-brightness-server
version: '0.1'
summary: Expose screen brightness control to local http server
description: |
  TBD.

grade: devel
confinement: devmode

parts:
  server:
    plugin: dump
    source: .
    stage:
      - main.py

apps:
  screen-brightness-server:
    command: python3 -u $SNAP/main.py
    daemon: simple
    restart-condition: always

