name: deskconn
version: git
summary: Expose your desktop functionalities over network
description: |
  Expose your desktop functionalities over network

grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64
    run-on: amd64

environment:
  PYTHONPATH: $PYTHONPATH:$SNAP/lib/python3.8/site-packages:$SNAP_COMMON/runtime/packages
  PATH: $PATH:$SNAP_COMMON/runtime/usr/bin

parts:
  launchers:
    plugin: dump
    source: .
    stage:
      - system.py
      - session.py
      - config.sh
    prime:
      - system.py
      - session.py
      - config.sh
  deskconn:
    plugin: nil
    source: .
    build-packages:
      - libdbus-1-dev
      - libdbus-glib-1-dev
      - software-properties-common
    override-build: |
      snapcraftctl build
      add-apt-repository ppa:deadsnakes/ppa -y -u
      apt install python3.8 python3.8-venv python3.8-dev -y
      python3.8 -m ensurepip
      python3.8 -m pip install --install-option="--prefix=$SNAPCRAFT_PART_INSTALL" .
      find $SNAPCRAFT_PART_INSTALL -type d -name __pycache__ -print0 | xargs -0 rm -rf

apps:
  deskconn:
    command: python3.8 -u $SNAP/system.py
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind
      - display-control
  session:
    command: python3.8 -u $SNAP/session.py
    plugs:
      - network
      - network-bind
      - x11
      - unity7
      - desktop
  config:
    command: config.sh

plugs:
  deskconnd-runtime:
    interface: content
    default-provider: deskconnd:runtime
    target: $SNAP_COMMON/runtime
  deskconnd-state:
    interface: content
    default-provider: deskconnd:state
    target: $SNAP_COMMON/state
