name: deskconn
version: git
summary: Expose your desktop functionalities over network
description: |
  Expose your desktop functionalities over network

grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: i386
    run-on: i386

  - build-on: armhf
    run-on: armhf

  - build-on: arm64
    run-on: arm64

environment:
  PYTHONPATH: $PYTHONPATH:$SNAP/lib/python3.6/site-packages:$SNAP_COMMON/runtime/lib/python3.6/site-packages
  PATH: $PATH:$SNAP_COMMON/runtime/usr/bin:$SNAP_COMMON/runtime/bin

parts:
  launchers:
    plugin: dump
    source: .
    stage:
      - system.py
      - session.py
      - config.sh
    prime:
      - system.py
      - session.py
      - config.sh
  deskconn:
    plugin: nil
    source: .
    build-packages:
      - libdbus-1-dev
      - libdbus-glib-1-dev
      - wget
      - python3-pip
    stage-packages:
      - libnotify-bin
    override-build: |
      snapcraftctl build
      python3 -O -m pip install --no-compile -U --prefix $SNAPCRAFT_PART_INSTALL .
      python3 -O -m compileall -b $SNAPCRAFT_PART_INSTALL
      find $SNAPCRAFT_PART_INSTALL -type f -name "*.py" -exec rm {} \;
      find $SNAPCRAFT_PART_INSTALL -type f -name "*.so" -exec strip -s {} \;

apps:
  deskconn:
    command: system.py
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind
      - display-control
  session:
    command: session.py
    plugs:
      - network
      - network-bind
      - x11
      - unity7
      - desktop
  config:
    command: config.sh

plugs:
  deskconnd-runtime:
    interface: content
    content: runtime
    default-provider: deskconnd:runtime
    target: $SNAP_COMMON/runtime
  deskconnd-state:
    interface: content
    content: state
    default-provider: deskconnd:state
    target: $SNAP_COMMON/state
