name: deskconn
version: git
summary: Expose your desktop functionalities over network
description: |
  Expose your desktop functionalities over network

grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: i386
    run-on: i386

  - build-on: armhf
    run-on: armhf

environment:
  PYTHONPATH: PYTHONPATH:$SNAP_COMMON/deskconnd-runtime-dir

parts:
  launchers:
    plugin: dump
    source: .
    stage:
      - system.py
      - session.py
      - config.sh
    prime:
      - system.py
      - session.py
      - config.sh
  deskconn:
    plugin: python
    source: .
    python-packages:
      - dbus-python
      - xlib
    build-packages:
      - libdbus-1-dev
      - libdbus-glib-1-dev

apps:
  deskconn:
    command: python3 -u $SNAP/system.py
    daemon: simple
    restart-condition: never
    plugs:
      - network
      - network-bind
      - display-control
  session:
    command: python3 -u $SNAP/session.py
    plugs:
      - network
      - network-bind
      - x11
      - unity7
      - desktop
  config:
    command: config.sh

plugs:
  deskconnd-sock-dir:
    content: socket-directory
    default-provider: deskconnd:sock-dir
    interface: content
    target: $SNAP_COMMON/deskconnd-sock-dir
  deskconnd-runtime-dir:
    content: executables
    default-provider: deskconnd:runtime-dir
    interface: content
    target: $SNAP_COMMON/deskconnd-runtime-dir
