name: deskconn
version: '0.5'
summary: Expose your desktop functionalities over network
description: |
  Expose your desktop functionalities over network

grade: stable
confinement: devmode

architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: i386
    run-on: i386

parts:
  server:
    plugin: dump
    source: .
    prime:
      - start-crossbar
      - crossbar-config
  autobahn:
    plugin: python
    source: .
    requirements: requirements.txt
    build-packages:
      - pkg-config
      - libdbus-1-dev
      - libdbus-glib-1-dev

apps:
  deskconn:
    command: python3 -u $SNAP/start-crossbar
    daemon: simple
    restart-condition: never
