name: screen-brightness-server
version: '0.3'
summary: Expose screen brightness control to local http server
description: |
  Expose screen brightness control to local http server

  Currently only supports machines with Intel GPU.

grade: stable
confinement: devmode

architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: i386
    run-on: i386

parts:
  server:
    plugin: dump
    source: .
    prime:
      - main.py
      - controller.py
      - component.py
      - constants.py
  autobahn:
    plugin: python
    python-packages:
      - autobahn[asyncio]

apps:
  screen-brightness-server:
    command: python3 -c "from crossbar import run; run(['--help'])"
    environment:
      PYTHONPATH: "$SNAP/crossbar:$PYTHONPATH"

plugs:
  crossbar:
    interface: content
    content: executables
    default-provider: crossbar:crossbar
    target: $SNAP/crossbar
