name: deskconn
version: '0.9'
summary: Expose your desktop functionalities over network
description: |
  Expose your desktop functionalities over network

grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: i386
    run-on: i386

  - build-on: armhf
    run-on: armhf

parts:
  launchers:
    plugin: dump
    source: .
    stage:
      - pair.py
      - server.py
      - session.py
      - config.sh
      - .crossbar
    prime:
      - pair.py
      - server.py
      - session.py
      - config.sh
      - .crossbar
  deskconn:
    plugin: python
    source: .
    requirements:
      - requirements.txt
    stage-packages:
      - libsnappy1v5
      - avahi-utils
    build-packages:
      - pkg-config
      - libdbus-1-dev
      - libdbus-glib-1-dev
      - gcc
      - libffi-dev
      - libssl-dev
      - make
      - libbz2-dev
      - libsnappy-dev
      - libunwind-dev

apps:
  deskconn:
    command: python3 -u $SNAP/server.py
    daemon: simple
    restart-condition: never
    plugs:
      - network
      - network-bind
      - display-control
      - avahi-control
  session:
    command: python3 -u $SNAP/session.py
    plugs:
      - network
      - network-bind
      - x11
      - unity7
      - desktop
  config:
    command: config.sh
  pair:
    command: python3 -u $SNAP/pair.py
    plugs:
      - network
      - network-bind

slots:
  deskconn-sock-dir:
    interface: content
    content: socket-directory
    write:
      - $SNAP_COMMON

plugs:
  services-content:
    content: avahi-services
    default-provider: avahi:services-content
    interface: content
    target: $SNAP_COMMON
