name: deskconn
version: '0.9'
summary: Expose your desktop functionalities over network
description: |
  Expose your desktop functionalities over network

grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: i386
    run-on: i386

parts:
  launchers:
    plugin: dump
    source: .
    prime:
      - server.py
      - session.py
      - config.sh
      - crossbar-config
  deskconn:
    plugin: python
    source: .
    requirements:
      - requirements.txt
    stage-packages:
      - libsnappy1v5
    build-packages:
      - pkg-config
      - libdbus-1-dev
      - libdbus-glib-1-dev
      - gcc
      - libffi-dev
      - libssl-dev
      - make
      - libbz2-dev
      - libsnappy-dev
      - libunwind-dev

apps:
  deskconn:
    command: server.py
    daemon: simple
    restart-condition: never
    plugs:
      - network
      - network-bind
      - display-control
  session:
    command: session.py
    plugs:
      - network
      - network-bind
      - x11
      - unity7
      - desktop
  config:
    command: config.sh
